language: node_js
node_js:
  - "7"
deploy:
  provider: npm
  email: "nicolas.dao@gmail.com"
  api_key: 
    secure: "rmdejuFtIbx8jjNsooVtPvfQs0Ltn74ycS7WqLL908Dzg755bxF9iu3y1+RANpCeoUWr2nIiqwHnHc6QRV/uo6MFiXSMpLv0OoPEy7ML5dSISouqox5zzE0Qx7O51QUamc0SUGMtZPIgeR/YglhjSUIpe5qesr23X7sgwroR7Hu3bnj3ormVADfXJAYgeO3Mi9lWnJO77J0eHdcur+/ODEApmERptcXAxn0g5XurAWRZGVial3Ioxqqa+dkRvMxZ8fjKByTSFBV7Y0zPxE/yXh0ef2GM0Km3MP0VqMq2F5mQunvaMMVZa0iooeBroRJh4+tOvmFvy05URnuXVV8lDYLcr0SgNNTItXguAFqOvdvII5Ys4OsTv+9GlsbPTP2Uq1FhOyvx5HztKRSwiPSGJCsfKeLSyI+YQUOyKKwP1zGbledF3/Hj9aVuiErLq06O7LjqFX7jSj6JshJmpQWV0Wphyd6rO+iMQZMpDQqh1KujWURVw4i6jPCw2m/BLsUrwdKXorYu6Xr8b5b08C+gEu6aol33GmymOVyrWQnXFwj37B1dAe4eir2bbf+Vyc0wpMJ/GiVh95RWG7yTUpBKrR41w+ancAvoBNG80jfTqbjNwfqrgoxQze6n+lFPkgRNkSSASQBbq0kBiZaShdO7tWJY2IqDLW0QMh54gbRUgKo="
  on:
    tags: true